files:
  - "SYSTEM"  

rules:
  - name: "Sudo Kullanimi"
    pattern: "sudo"
    type: "info"
  - name: "SSH Failed"
    pattern: "Failed password"
    type: "security"
  - name: "Error"
    pattern: "error"
    type: "warning"